steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: 
    - 'app'
    - 'deploy'
    - 'app.yaml'
    - '--quiet'
    - '--stop-previous-version'
    - "--version=$(echo ${TAG_NAME} | sed 's/\\./_/g')"
timeout: "1600s"
