steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: bash
  args: 
    - '-c'
    - |
      gcloud app deploy app.yaml --quiet -v $(echo $TAG_NAME | sed 's/\./-/g')
timeout: "1600s"
